// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSLmoecvGTnhZkq6fqsbYAAfENYtoN8AY',
    appId: '1:643983694000:web:38d8f796776df12f108375',
    messagingSenderId: '643983694000',
    projectId: 'registrationaccesscontrol',
    authDomain: 'registrationaccesscontrol.firebaseapp.com',
    storageBucket: 'registrationaccesscontrol.appspot.com',
    measurementId: 'G-LZPEVFQVMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB48mA5UYs7U1TBGlemUGxCTxrXLqDRZlY',
    appId: '1:643983694000:android:bcc3b5d4b5e5a7ed108375',
    messagingSenderId: '643983694000',
    projectId: 'registrationaccesscontrol',
    storageBucket: 'registrationaccesscontrol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIyQmvKIlmPKvbZz3WJemFKeJxnMFfJgI',
    appId: '1:643983694000:ios:b30256bd7ca5190b108375',
    messagingSenderId: '643983694000',
    projectId: 'registrationaccesscontrol',
    storageBucket: 'registrationaccesscontrol.appspot.com',
    iosClientId: '643983694000-up8m1pa9svo54qmbbj5e5dmfalfo111m.apps.googleusercontent.com',
    iosBundleId: 'com.example.access',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIyQmvKIlmPKvbZz3WJemFKeJxnMFfJgI',
    appId: '1:643983694000:ios:b30256bd7ca5190b108375',
    messagingSenderId: '643983694000',
    projectId: 'registrationaccesscontrol',
    storageBucket: 'registrationaccesscontrol.appspot.com',
    iosClientId: '643983694000-up8m1pa9svo54qmbbj5e5dmfalfo111m.apps.googleusercontent.com',
    iosBundleId: 'com.example.access',
  );
}
